name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Build
      run: dotnet publish -c Release
    
    - name: Download Inno Setup
      run: |
        curl -L -o is.exe https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe
        .\is.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    
    - name: Build Installer
      run: |
        & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installer\idis-converter-installer.iss
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: installer
        path: installer\Output\idis-converter-setup.exe
